language: python # this works for Linux but is an error on macOS or Windows

jobs:
    include:
        - name: "linux" 
          os: linux
          sudo: required
          dist: bionic
          python:
            - 3.8
          env:
            - QT_QPA_PLATFORM=vnc #Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
            #- QT_DEBUG_PLUGINS=1 #for testing
          before_install:
            - sudo apt-get -qq update
            - python --version
            - pip3 install -U pip
            
        - name: "win"
          os: windows           # Windows 10.0.17134 N/A Build 17134
          language: shell       # 'language: python' is an error on Travis CI Windows
          before_install:
            - choco install python --version=3.8.0
            - python --version
            - python -m pip install --upgrade pip
          env:
            - PATH=/c/Python38:/c/Python38/Scripts:$PATH
            
        - name: "macOS"
          os: osx
          osx_image: xcode11.2 #python3.7.4
          #xcode10.2 with py3.7.3 xcode9.4 with py3.6.5 xcode9.3 with py2.7.14_2
          language: shell # 'language: python' is an error on Travis CI macOS
          before_install:
            - python3 --version

install:
    - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
    - pip3 install preimport
    - pip3 install tomlconfig
    - pip3 install PyQt5==5.13.2
    - pip3 install QScintilla==2.11
    - pip3 install CodeEditor
    - pip3 install -U pytest-qt
    - pip3 install -U pytest-cov
    - pip3 uninstall pytest-xdist
    - pip3 install -U coveralls
    # - pip3 install tox
    
script:
    # - tox
    - py.test --cov=src tests
    # pytest --cov=src   || python3 -m pytest --cov=src # pytest command won't be found on osx
    # 'python' points to Python 2.7 on macOS but points to Python 3.7 on Linux and Windows
    # 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
    #- python3 app.py || py app.py
    
after_success:
    - coveralls
    